FROM golang:1.21.3-alpine3.18

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download && go mod verify

COPY . ./

WORKDIR /app/cmd/ecommerce-backend-go

RUN go build -o ecommerce-backend-go

EXPOSE 8080

CMD ["./ecommerce-backend-go"] 